import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { TMDB_BASE_URL, LANGUAGE, CERTIFICATION_APPEND } from "./tmdbConfig";
import getAdaptations from "./getAdaptations";
import getBookKeywords from "./getBookKeywords";
import getSortParams from "./getSortParams";
import { mapTitleDetails, mapTitleList } from "./tmdbMappers";

// ===== TMDb service =====
// All requests to TMDb go through this service.
// mediaType is either "movie" or "tv", since TMDb has separate endpoints for them.

export const tmdbApi = createApi({
  reducerPath: "tmdbApi",
  baseQuery: fetchBaseQuery({
    baseUrl: TMDB_BASE_URL,
    // TMDb expects the read access token as a Bearer token
    prepareHeaders: (headers) => {
      headers.set("Authorization", `Bearer ${import.meta.env.VITE_TMDB_TOKEN}`);
      return headers;
    },
  }),
  endpoints: (builder) => ({
    // --- Discover ---
    // Book adaptations, optionally filtered by genres and an extra keyword.
    // An infinite query keeps every loaded page, so "Load more" can add the next one.
    discoverTitles: builder.infiniteQuery({
      infiniteQueryOptions: {
        initialPageParam: 1,
        // Returns the next page number, or undefined when there are no more pages
        getNextPageParam: (lastPage) =>
          lastPage.page < lastPage.totalPages ? lastPage.page + 1 : undefined,
      },
      query: ({ queryArg, pageParam }) => ({
        url: `discover/${queryArg.mediaType}`,
        params: {
          // The extra keyword is used for categories without a TV genre
          with_keywords: getBookKeywords(queryArg.keywords),
          // An empty string means no filter, so the param is left out
          with_genres: queryArg.genres || undefined,
          // Explore leaves sort out and gets the most popular first
          ...getSortParams(queryArg.mediaType, queryArg.sort),
          page: pageParam,
          language: LANGUAGE,
        },
      }),

      // For infinite queries the third argument holds both queryArg and pageParam
      transformResponse: (response, meta, { queryArg }) =>
        mapTitleList(response, queryArg.mediaType),
    }),

    // --- Adaptation search ---
    // Searches movies and series and keeps only book adaptations
    searchAdaptations: builder.query({ queryFn: getAdaptations }),

    // --- Details ---
    // Credits and videos are included to get cast and trailers in one request
    getTitleDetails: builder.query({
      query: ({ mediaType, id }) => ({
        url: `${mediaType}/${id}`,
        params: {
          append_to_response: `credits,videos,${CERTIFICATION_APPEND[mediaType]}`,
          language: LANGUAGE,
        },
      }),
      transformResponse: (response, meta, { mediaType }) =>
        mapTitleDetails(response, mediaType),
    }),

    // --- Genres ---
    getGenres: builder.query({
      query: (mediaType) => ({
        url: `genre/${mediaType}/list`,
        params: { language: LANGUAGE },
      }),
    }),
  }),
});

// Generated by RTK Query from the endpoint names
export const {
  useDiscoverTitlesInfiniteQuery,
  useSearchAdaptationsQuery,
  useGetTitleDetailsQuery,
  useGetGenresQuery,
} = tmdbApi;
