import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { TMDB_BASE_URL, BOOK_KEYWORD_ID, LANGUAGE } from "./tmdbConfig";
import { mapTitleList } from "./tmdbMappers";

// ===== TMDb service =====
// All requests to TMDb go through this service.
// mediaType is either "movie" or "tv", since TMDb has separate endpoints for them.

export const tmdbApi = createApi({
  reducerPath: "tmdbApi",
  baseQuery: fetchBaseQuery({
    baseUrl: TMDB_BASE_URL,
    // TMDb expects the read access token as a Bearer token
    prepareHeaders: (headers) => {
      headers.set("Authorization", `Bearer ${import.meta.env.VITE_TMDB_TOKEN}`);
      return headers;
    },
  }),
  endpoints: (builder) => ({
    // --- Discover ---
    // Book adaptations, optionally filtered by genre
    discoverTitles: builder.query({
      query: ({ mediaType, page = 1, genres }) => ({
        url: `discover/${mediaType}`,
        params: {
          with_keywords: BOOK_KEYWORD_ID,
          // An empty string means no filter, so the param is left out
          with_genres: genres || undefined,
          sort_by: "popularity.desc",
          page,
          language: LANGUAGE,
        },
      }),

      // The third argument is the same object the query was called with
      transformResponse: (response, meta, { mediaType }) =>
        mapTitleList(response, mediaType),
    }),

    // --- Search ---
    searchTitles: builder.query({
      query: ({ mediaType, searchTerm, page = 1 }) => ({
        url: `search/${mediaType}`,
        params: { query: searchTerm, page, language: LANGUAGE },
      }),
      transformResponse: (response, meta, { mediaType }) =>
        mapTitleList(response, mediaType),
    }),

    // --- Details ---
    // Credits and videos are included to get cast and trailers in one request
    getTitleDetails: builder.query({
      query: ({ mediaType, id }) => ({
        url: `${mediaType}/${id}`,
        params: {
          append_to_response: "credits,videos",
          language: LANGUAGE,
        },
      }),
    }),

    // --- Genres ---
    getGenres: builder.query({
      query: (mediaType) => ({
        url: `genre/${mediaType}/list`,
        params: { language: LANGUAGE },
      }),
    }),
  }),
});

// Generated by RTK Query from the endpoint names
export const {
  useDiscoverTitlesQuery,
  useSearchTitlesQuery,
  useGetTitleDetailsQuery,
  useGetGenresQuery,
} = tmdbApi;
